operator:
    address: 0x971191c4fCBB7F23b2df511C4b61c2640cB6a605
    earnings_receiver_address: 0x43fB7Cbc0CA334B4030Eb631BFfBeE13bE7bAF6E
    delegation_approver_address: 0x0000000000000000000000000000000000000000
    staker_opt_out_window_blocks: 0
    metadata_url: "https://drive.google.com/file/d/1RFjuEJUrnedFFLNDNf9X0NF-G5WnScFD/view?usp=share_link"
el_slasher_address: 0xD11d60b669Ecf7bE10329726043B3ac07B380C22
bls_public_key_compendium_address: 0xc81d3963087Fe09316cd1E032457989C7aC91b19
eth_rpc_url: https://eth-goerli.g.alchemy.com/v2/BLF-lbEhfy-5mNMgYYBSReArYwK23ePV
private_key_store_path: /root/.eigenlayer/operator_keys/keyecsda.ecdsa.key.json
signer_type: local_keystore
bls_private_key_store_path: /root/.eigenlayer/operator_keys/keybls.bls.key.json
chain_id: 5
